### PR TITLE
Heather dev

### PR DESCRIPTION
**Pull request by heatherm**
[x] Add envrc
[x] Simplify database.yml
[x] Update secret_token to be different from sf72
[x] Remove all sf72 references that are easy
[ ] Add feature specs
[ ] Move to Ruby 2
[ ] Bump rails

### CODE REVIEW

**Comment by arena** [comment]
Yay!! Is there a deploy of this branch someplace? If not I can deploy it and then accept the pull request.

**Comment by arena** [comment]
I deployed it. It deploys just fine. I don't know how to interpret a lot of the very technical stuff but it makes me happy. :)

Some of the things that changed from City72 to Ready96 are confusing. For instance there is not "Ready96 Toolkit" ... The City72 Toolkit is this site toolkit.sf72.org and we should still link to it. And in this project, City72 is the generic name for the site. 

Is it possible to bring back the SF72 and City72 references. I've done a lot of the removal in the copy and outward appearance of the site already (where appropriate).

**Comment by arena** [comment]
ps - there are some references to SF72 in the code that are weird ... those can go, but it might be tedious to find them and I don't know what they should be... something generic in case somebody forks Ready96 to make a City72 site of their own for a city, county, or other community.

**Comment by heatherm** [comment]
I see. No problem to revert 😀

**Comment by heatherm** [comment]
@arena I reverted the toolkit rename, so I think we're good to go. Anything else you want removed?

**Pull request merged**
